.TH "C:/Users/sonny/Desktop/tmpo/lynxarm_srvcli/src/LowLevelDriver.h" 3 "Version 1" "LynxMotion AL5D Hardware Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/sonny/Desktop/tmpo/lynxarm_srvcli/src/LowLevelDriver.h \- Contains the declaration of the \fBLowLevelDriver\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <string>\fP
.br
\fR#include <queue>\fP
.br
\fR#include <boost/asio\&.hpp>\fP
.br
\fR#include 'Configuration\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLowLevelDriver\fP"
.br
.RI "Represents a low-level driver for communication with a robot arm\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains the declaration of the \fBLowLevelDriver\fP class\&. 

The \fBLowLevelDriver\fP class provides functionality for sending serial messages, controlling servo positions, setting position offsets, queuing commands, and processing the command queue\&. It uses the Boost\&.Asio library for asynchronous I/O operations and provides an interface for interacting with a robot arm\&.
.PP
\fBAuthor\fP
.RS 4
Sonny Selten 
.PP
Elviana 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2024-03-07 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for LynxMotion AL5D Hardware Interface from the source code\&.
